language: java
jdk:
  - oraclejdk8
branches:
  only:
   - android
before_install:
  - openssl enc -d -aes-256-cbc -md md5 -k ${FILE_PASSWORD} -in travis/secring.gpg.enc -out travis/secring.gpg && ls -l && ${TRAVIS_BUILD_DIR}/gradlew --version
install: true
script:
  - cd ${TRAVIS_BUILD_DIR}
  - ./gradlew -x test uploadArchives -PossrhUsername=zakgof -PossrhPassword=${OSSRH_PASSWORD} -Psigning.keyId=${SIGNING_KEY_ID} -Psigning.password=${SIGNING_PASSWORD} -Psigning.secretKeyRingFile=${TRAVIS_BUILD_DIR}/travis/secring.gpg
